//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsaDotnetBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.LineItems = new HashSet<LineItem>();
            this.ReimbursementReceipts = new HashSet<ReimbursementReceipt>();
        }
    
        public int ReceiptId { get; set; }
        public Nullable<System.Guid> UserObjectId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> IsScanned { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string ImageRef { get; set; }
        public string OcrRef { get; set; }
        public bool WaitingForOcr { get; set; }
        public bool Provisional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineItem> LineItems { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReimbursementReceipt> ReimbursementReceipts { get; set; }
    }
}
