//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsaDotnetBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reimbursement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reimbursement()
        {
            this.ReimbursementReceipts = new HashSet<ReimbursementReceipt>();
        }
    
        public int ReimbursementId { get; set; }
        public int AccountId { get; set; }
        public bool IsReimbursed { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReimbursementReceipt> ReimbursementReceipts { get; set; }
    }
}
