//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsaDotnetBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReimbursementReceipt
    {
        public int ReceiptId { get; set; }
        public int ReimbursementId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Receipt Receipt { get; set; }
        public virtual Reimbursement Reimbursement { get; set; }
    }
}
