//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsaDotnetBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingListItem
    {
        public int ShoppingListItemId { get; set; }
        public int ShoppingListId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> StoreId { get; set; }
        public bool Checked { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ShoppingList ShoppingList { get; set; }
        public virtual Store Store { get; set; }
    }
}
